# Generated by Django 5.2.3 on 2025-06-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
